config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  resources :solvents
  
  resources :substances do
    member do
      get :molecule
      get :new_dilution
      post :add_dilution_to_blend
    end
    collection do
      get :new_dilution
      get :suggest
      get :report
      put :refresh_elastic
    end
  end
  
  resources :blends do
    member do
      post :bottle
      post :adjust
      post :resize
      get :dilute
      get :print
      put :detach_families
    end
    collection do
      get :memorize
      put :refresh_elastic
    end
  end
  
  resources :families do
    member do
      get :add_blends
    end
  end
  
  resources :olfactive_families, controller: "olfactive_families"
  
  resource :mixing, :controller => "mixing" do
    member do
      get :new
      post :prepare
      get :prepare
      post :create
      get :update_final_concentration
    end
  end

  resources :separating do
    member do
      get :prepare
      post :create
    end
  end
  
  resource :analyzer, controller: "analyzer" do
    get :comparison
    get :new
  end
  
  resources :notes
  
  resource :search, :controller => "search"
  
  resource :welcome, :controller => "welcome" do
    get :help
  end
  
  match "set/:key/:value", :controller => "welcome", :action => "set_session_variables", via: [:get, :post]
  
  
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  
  validates :name, uniqueness: true
  validates :name, :tags, :body, :presence => true
  
  
  def to_s
    name
  end
  
end

app/controllers/notes_controller.rb
class NotesController < InheritedResources::Base
  
  
  private
  
  def note_params
    # It's mandatory to specify the nested attributes that should be whitelisted.
    # If you use `permit` with just the key that points to the nested attributes hash,
    # it will return an empty hash.
    params.require(:note).permit(:name, :tags, :body, :links)
   end

end
  

app/views/notes/_form.html.erb
<%= render 'form_group_error_messages' %>

<div class="form-group form-group-lg">
    <%= f.label :name, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_field :name, :class => "form-control", :style => "font-weight: bold;" %>
    </div>
</div>
<hr/>
<div class="form-group">
    <%= f.label :tags, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_area :tags, :class => "form-control" %>
    </div>
</div>
<hr/>
<div class="form-group">
    <%= f.label :links, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_area :links, :class => "form-control" %>
    </div>
</div>
<hr/>
<div class="form-group">
    <%= f.label :body, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_area :body, :class => "form-control", rows: 5 %>
    </div>
</div>



<% content_for :panel_footer do %>
    Add the name of Substances or Blends wrapped by brackets, like "Ebanol" into the links field and they will become clickable. Alternatively you can use dom_ids like "blend_33". 
<% end %>


<% content_for :form_submit_controls do %>
    <div class="form-inline">
        <div class"form-group">
            <%= f.submit submit_label, :class => "btn btn-#{submit_class ||= :success} col-sm-offset-9 col-sm-3" %>
        </div>
    </div>
<% end %>

app/views/notes/_list.html.erb
<table class="table table-condensed">
    <thead>
        <tr>
            <th><%= resource_class.human_attribute_name :name %></th>
            <th><%= resource_class.human_attribute_name :created_at %></th>
            <th><%= resource_class.human_attribute_name :tags %></th>
        </tr>
    </thead>
    <tbody>
        <%= render collection %>
    </tbody>
</table>

app/views/notes/_note.html.erb
<tr>
    <td>
        <%= link_to note.name, note_path(note), style: "width: 100%; display:block;" %>
    </td>
    <td>
        <%= note.created_at %>
    </td>
    <td>
        <%= note.tags %>
    </td>
</tr>

app/views/notes/index.html.erb
<div class="panel panel-primary <%= resource_class_name %>">
    <div class="panel-heading">
        <h3 class="panel-title">
            <%= resource_class.count %> <%= resource_class.model_name.human(count: resource_class.count) %>
            <%= link_to new_note_path, style: "float:right;" do %>
                <span class="glyphicon glyphicon-plus"></span>
            <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <%= render 'list' %>
    </div>
    <div class="panel-footer">
        <%= link_to new_note_path, :class => "btn btn-success" do %>
            <span class="glyphicon glyphicon-plus"></span> Add 
        <% end %>
    </div>
</div>

app/views/notes/show.html.erb
<div class="panel panel-primary <%= resource_class_name %>">
    <div class="panel-heading">
        <h3 class="panel-title">
            <%= link_to edit_resource_path(resource), style: 'float: right;', title: "Edit", :'data-toggle' => "tooltip" do %>
                <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= resource.name %>, <span style="font-size: 11px;"><%= resource.created_at %></span>
        </h3>
    </div>
    <div class="panel-body">
       <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:tags), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= resource.tags %>
            </div>
        </div>
        <hr/>
        <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:links), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= simple_format stream_resource_links resource.links %>
            </div>
        </div>
        <hr/>
        <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:body), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= tabbed resource.body %>
            </div>
        </div>
    </div>
    <div class="panel-footer">
    </div>
</div>
<p>
    <%= link_to notes_path, :class => "btn btn-default" do %>
        <span class="glyphicon glyphicon-th-list"></span> Index
    <% end %>
</p>