config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  resources :solvents
  
  resources :substances do
    member do
      get :molecule
      get :new_dilution
      post :add_dilution_to_blend
    end
    collection do
      get :new_dilution
      get :suggest
      get :report
      put :refresh_elastic
    end
  end
  
  resources :blends do
    member do
      post :bottle
      post :adjust
      post :resize
      get :dilute
      get :print
      put :detach_families
    end
    collection do
      get :memorize
      put :refresh_elastic
    end
  end
  
  resources :families do
    member do
      get :add_blends
    end
  end
  
  resources :olfactive_families, controller: "olfactive_families"
  
  resource :mixing, :controller => "mixing" do
    member do
      get :new
      post :prepare
      get :prepare
      post :create
      get :update_final_concentration
    end
  end

  resources :separating do
    member do
      get :prepare
      post :create
    end
  end
  
  resource :analyzer, controller: "analyzer" do
    get :comparison
    get :new
  end
  
  resources :notes
  
  resource :search, :controller => "search"
  
  resource :welcome, :controller => "welcome" do
    get :help
  end
  
  match "set/:key/:value", :controller => "welcome", :action => "set_session_variables", via: [:get, :post]
  
  
  

end

app/models/concerns/substance/searchable.rb
module Substance::Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    index_name table_name

    mapping do
      indexes :name, analyzer: 'english', index_options: 'offsets'
      indexes :name_suggest, type: 'completion', payloads: true, index_analyzer: "simple", search_analyzer: "simple"
      indexes :tags_suggest, type: 'completion', payloads: true, index_analyzer: "simple", search_analyzer: "simple"
      indexes :cas, analyzer: 'english', index_options: 'offsets'
      indexes :alt_names, analyzer: 'english', index_options: 'offsets'
      indexes :sensory_tags, analyzer: 'english', index_options: 'offsets'
      indexes :notes, analyzer: 'english', index_options: 'offsets'
      indexes :notes_alt_1, analyzer: 'english', index_options: 'offsets'
      indexes :notes_alt_2, analyzer: 'english', index_options: 'offsets'
      indexes :vp_mmHg_25C, type: 'float'
    end


  end
  
  

  def as_indexed_json(options = {})
     {
       name: name,
       cas: cas,
       alt_names: alt_names,
       sensory_tags: sensory_tags,
       notes: notes,
       notes_alt_1: notes_alt_1,
       notes_alt_2: notes_alt_2,
       vp_mmHg_25C: vp_mmHg_25C,
       name_suggest: {
         input: name.split(/\b/),
         output: name,
         payload: {
           resource_id: id,
           character: character
         }
       },
       tags_suggest: {
         input: sensory_tags.split(/\b/),
         output: name,
         payload: {
           resource_id: id,
           character: character
         }
       }
     }
   end

end

app/models/substance.rb
class Substance < ActiveRecord::Base
 
  include Substance::Searchable
  include CasAble
  
  IFRA_LIMIT_CONCENTRATIONS = [ 0.317, 0.214, 0.13, 0.08, 0.107, 0.053, 0.032, 0.0267, 0.025, 0.019, 0.016, 0.014, 0.0104, 0.01, 0.005, 0.004, 0.002, 0.001, 0.0002 ]
  TENACITY_CATs = %w(base base-heart heart heart-top top)
  
  CURRENCIES = {
    :GBP => 0.71,
    :EUR => 1,
    :USD => 1.06
  }
  
  scope :order_alphabetical, lambda { order("#{self.table_name}.name ASC") }
  scope :order_character, -> { unscoped.order("#{self.table_name}.character ASC").order("#{self.table_name}.name ASC") }
  scope :order_vp, -> { unscoped.order("#{self.table_name}.vp_mmHg_25C ASC").order("#{self.table_name}.character ASC").order("#{self.table_name}.name ASC") }
  default_scope lambda { order_alphabetical }
  scope :visible, lambda { where("1=1")}
  scope :hidden, lambda { where("0=1")}

  has_many :dilutions
  has_many :ingredients, dependent: :restrict_with_error
  has_many :blends, through: :ingredients
  has_many :olfactive_families_substances
    
  accepts_nested_attributes_for :dilutions, allow_destroy: true # reject_if: proc { |attributes| attributes['title'].blank? }
  
  validates :name, :cas, uniqueness: true, allow_blank: true
  validates :name, :sensory_tags, :presence => true
  validates :ifra_cat_4_limit, numericality: { greater_than_or_equal_to: 0, less_than: 1 }, allow_blank: true
  
  validates_associated :dilutions
  
  
  def price_in_eur_per_100g
    price_in_currency_per_100g / CURRENCIES[price_currency.to_sym] rescue nil
  end
  
  def price_in_currency_per_100g
    price_per_quantity * (100.0 / quantity_in_gram_of_raw_material ) rescue nil
  end
  
  def to_s
    name
  end
  
  def alt_names
    if block_given?
      self[:alt_names].split(';').each{ |n| yield n.strip }
    else
      self[:alt_names]
    end
  end
  
  protected

end

app/controllers/substances_controller.rb
class SubstancesController < InheritedResources::Base
  
  respond_to :tex
  
  def index
    respond_to do |format|
      format.tex
      format.html
    end
  end
  
  def report
    @style = :report
    respond_to do |format|
      format.tex { render :action => :index }
    end
  end

  def create
    create! do |success, failure|
      success.html { redirect_after_save }
    end
  end
  
  def update
    update! do |success, failure|
      success.html { redirect_after_save }
    end
  end
  
  def suggest
    @suggest = substance_auto_suggest params[:suggest].gsub(/\W+/,' ') rescue nil
    @blends_suggest = blends_auto_suggest params[:suggest].gsub(/\W+/,' ') rescue nil
  end
  
  def refresh_elastic
    respond_to do |format|
      format.js do
        Substance.import force: true
        render js: "$('a.refresh-elastic').remove();"
      end
    end
  end
  
  def add_dilution_to_blend
    respond_to do |format|
      format.js do
        begin
          blend = Blend.find(params[:blend_id])
          @dilution = Dilution.find(params[:dilution_id])
          blend.ingredients << Ingredient.new(:dilution_id => @dilution.id, :substance_id => resource.id, :amount => 1)
        rescue Exception => e
          render :js => "alert('error: #{e.message}');"
        end
      end
    end
  end

  def molecule
    cas = nil
    resource.cas do |c|
      cas = c
      break
    end
    cas = params[:cas] if params[:cas].present?
    send_data Molpic.fetch(cas), type: "image/jpeg", disposition: "inline"
  end

  protected
  
  def substance_auto_suggest(string)
    response = Elasticsearch::Persistence.client.suggest \
      index: Substance.index_name,
      body: {
        substances_suggest: {
          text: string,
          completion: { field: 'name_suggest', size: 9 },
        },
        substances_suggest_tags: {
          text: string,
          completion: { field: 'tags_suggest', size: 13 }
        }
      }
    result = {}
    return {} unless response["substances_suggest"]
    response["substances_suggest"].first["options"].each do |item|
      result[ item["payload"]["resource_id"] ] = {
        name: item["text"],
        character: item["payload"]["character"]
      }
    end
    response["substances_suggest_tags"].first["options"].each do |item|
      result[ item["payload"]["resource_id"] ] = {
        name: item["text"],
        character: item["payload"]["character"]
      }
    end
    result
  end
  
  def blends_auto_suggest(string)
    response = Elasticsearch::Persistence.client.suggest \
      index: Blend.index_name,
      body: {
        blends_suggest: {
          text: string,
          completion: { field: 'name_suggest', size: 21 }
        }
      }
    result = {}
    return {} unless response["blends_suggest"]
    response["blends_suggest"].first["options"].each do |item|
      result[ item["payload"]["resource_id"] ] = {
        name: item["text"],
        color: item["payload"]["color"]
      }
    end
    result
  end

  def redirect_after_save
    logger.info "redirect_after_save"
    if params[:create_new_after].in? ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES
      logger.info "redirect_after_save TRUE"
      flash[:notice] = [resource.name, "saved"]
      redirect_to :action => :new, :create_new_after => "1"
    else
      redirect_to :action => :show, :id => resource.id
    end
  end
  
  private
  
  def substance_params
    # It's mandatory to specify the nested attributes that should be whitelisted.
    # If you use `permit` with just the key that points to the nested attributes hash,
    # it will return an empty hash.
    params.require(:substance).permit(:name, :cas, :sensory_tags, :alt_names, :notes, :notes_alt_1, :notes_alt_2, :ifra_cat_4_limit, :character,
      :price_per_quantity, :price_currency, :quantity_in_gram_of_raw_material, :vp_mmHg_25C,
      dilutions_attributes: [:solvent_id, :concentration, :intensity, :_destroy, :id]
    )
   end
end

app/views/substances/_add_to_blend_modal.html.erb
<div class="modal fade" id="add-to-blend-modal" tabindex="-1" role="dialog" aria-labelledby="Add to Blend Modal" aria-hidden="true">
    <div class="modal-dialog">
        <%= form_tag add_dilution_to_blend_substance_path(resource), :remote => true do %>
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add to blend</h4>
                </div>
                <div class="modal-body">
                    <p>
                        Select the blend to which you would like to add this dilution
                    </p>
                    <div>
                        <%= label_tag :blend_id, Blend.model_name.human %>
                        <%= select_tag :blend_id, options_for_select( Blend.all.order_updated_at.collect { |b| [ b.name, b.id ] }), class: "form-control blend"  %>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t :'global.cancel' %></button>
                    <button type="submit" class="btn btn-primary"><%= t :'global.add' %> <span class="glyphicon glyphicon-plus"></span></button>
                </div>
            </div>
            <%= hidden_field_tag :dilution_id, nil, class: 'dilution_id' %>
        <% end %>
    </div>
</div>

app/views/substances/_dilution_form.html.erb
    <%= f.fields_for :dilutions do |fd| %>
        <%= render "dilutions/form", :fd => fd, :f => f %>
    <% end %>

app/views/substances/_form.html.erb
<%= render 'form_group_error_messages' %>

<div class="form-group form-group-lg">
    <%= f.label :name, :class => "col-sm-3 control-label" %>
    <div class="col-sm-6">
        <%= f.text_field :name, :class => "form-control", :style => "font-weight: bold;", autocomplete: "off" %>
    </div>
    <div class="col-sm-3" style="text-align: right;">
        <div class="btn-group">
            <button type="button" data-color-selector="list" class="btn btn-default dropdown-toggle <%= "color-#{resource.character}" if resource.character.present? %>" data-toggle="dropdown">
                <span class="button-title">
                    <span style="font-weight: bold; opacity: 0.7;" class="name"><%= resource.character.to_s.upcase %></span>
                </span><span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" style="padding:1px 1px 0; left:auto; right:0; ">
                <% substance_character.each do |name, s| %>
                    <li>
                        <!-- ONCLICK -->
                        <%= link_to "#", class: "color-#{name}", style: "border-bottom:1px solid #fff;", :'data-name' => name, :'data-color-selector' => 'list' do %>
                            <span style="font-weight: bold; opacity: 0.7;"><%= name.upcase %></span> <span style="font-size: 11px; opacity: 0.6"><%= s.first %></span>
                        <% end %>
                    </li>
                <% end %>
            </ul>
            <%= f.hidden_field :character, class: 'character'  %>
        </div>
    </div>
</div>
<hr/>
<div class="form-group">
    <%= f.label :cas, :class => "col-sm-3 control-label" %>
    <div class="col-sm-3">
        <%= f.text_field :cas, :class => "form-control", autocomplete: "off" %>
    </div>
</div>
<hr/>
<div class="form-group">
    <%= f.label :alt_names, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_field :alt_names, :class => "form-control", autocomplete: "off" %>
    </div>
</div>
<hr/>

<div class="form-group">
    <%= f.label :ifra_cat_4_limit, :class => "col-sm-3 control-label" %>
    <div class="col-sm-3">
        <%= f.text_field :ifra_cat_4_limit, list: :ifra_cat_4_limits, placeholder: "unregulated", class: "form-control", autocomplete: "off",
            value: number_with_precision(resource.ifra_cat_4_limit, precision: 9, strip_insignificant_zeros: true) %>
        <datalist id="ifra_cat_4_limits">
            <%= options_for_select Substance::IFRA_LIMIT_CONCENTRATIONS.collect{ |s| [ "#{number_with_precision( s * 100, precision: 3)} %", number_with_precision(s, precision: 7, strip_insignificant_zeros: true) ] } %>
        </datalist>
    </div>
</div>
<hr/>

<div class="form-group">
    <%= f.label :vp_mmHg_25C, :class => "col-sm-3 control-label" %>
    <div class="col-sm-3">
        <%= f.text_field :vp_mmHg_25C, class: "form-control", autocomplete: "off", precision:9, strip_insignificant_zeros: true %>
    </div>
</div>
<hr/>

<div class="form-group">
    <%= f.label :price, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_field :price_per_quantity, placeholder: :default, class: "form-control", style: "width: 6em; float:left; text-align: right;", autocomplete: "off" %>
        <%= f.select :price_currency, Substance::CURRENCIES.collect { |k,v| [ k, k ] }, {}, class: "form-control", style: "width: 5em; float:left; margin: 0 1em;"  %>
        <div class="input-group">
           <div class="input-group-addon">per</div>
           <%= f.text_field :quantity_in_gram_of_raw_material, placeholder: :default, class: "form-control", style: "text-align: right;", autocomplete: "off" %>
            <div class="input-group-addon">gram of raw material</div>
         </div>
    </div>
</div>
<hr/>

<%= render 'text_area_form_group', f: f, c: :sensory_tags %>
<%= render 'text_area_form_group', f: f, c: :notes, opt: { rows: 5 } %>
<%= render 'text_area_form_group', f: f, c: :notes_alt_1, opt: { rows: 5 } %>
<%= render 'text_area_form_group', f: f, c: :notes_alt_2, opt: { rows: 5 } %>

<div class="dilution-form">
    <%= render "dilution_form", :f => f %>
</div>


<% content_for :panel_header_right do %>
<% end %>

<% content_for :panel_footer do %>
    <div class"form-group">
        <%= f.link_to_add :dilutions, class: "btn btn-default", :data => { :target => ".dilution-form" } do %>
            <span class="glyphicon glyphicon-plus-sign"></span> <%= t :'global.add_dilution' %>
        <% end %>
    </div>
<% end %>

<% content_for :form_submit_controls do %>
    <div class="form-inline">
        <div class"form-group">
            <div class="col-sm-3 col-sm-offset-6 control-label checkbox">
                <%= label_tag :create_new_after, t(:'global.create_new_after') %>
                <%= check_box_tag :create_new_after, 1, params[:create_new_after] %>
            </div>
            <%= f.button class: "btn btn-#{submit_class ||= :success} col-sm-3" do -%>
                <i class="fa fa-floppy-o"></i> <%= submit_label %>
            <% end -%>
        </div>
    </div>
<% end %>

app/views/substances/_list.html.erb
<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th><%= resource_class.human_attribute_name :name %></th>
            <th><%= resource_class.human_attribute_name :cas %></th>
            <th><%= resource_class.human_attribute_name :ifra_cat_4_limit %></th>
            <th><%= resource_class.human_attribute_name :sensory_tags %></th>
            <th class="r"><%= resource_class.human_attribute_name :vp_mmHg_25C %></th>
            <th class="r">price per <br/>100 gram</th>
        </tr>
    </thead>
    <tbody>
        <%= render collection %>
    </tbody>
</table>

app/views/substances/_new_dilution.html.erb
<% form_for resource, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
    <% @dummy = f %>
<% end %>

<%= render "dilution_form", :f => @dummy %>

app/views/substances/_substance.html.erb
<tr>
    <%= content_tag :td, colored(substance) do %>
        <%= link_to substance.name, substance_path(substance), style: "width: 100%; display:block; color:rgba(0,0,0,0.7);" %>
    <% end %>
    <td>
        <%= substance.cas %>
    </td>
    <td>
        <%= "#{substance.ifra_cat_4_limit * 100}<span class='small-unit'> %</span>".html_safe rescue nil %>
    </td>
    <td>
        <%= substance.sensory_tags %>
    </td>
    <td class="r">
        <%= number_with_precision substance.vp_mmHg_25C, precision:9, strip_insignificant_zeros: true %>
    </td>
    <td class="r">
        <%= number_with_precision substance.price_in_eur_per_100g, precision:0 %>
    </td>
</tr>

app/views/substances/_used_in_blends.html.erb
<span class="col-sm-2 small-label">
    <%= t :'global.used_in' %> <%= Blend.model_name.human(count: 2) %>
</span>
<div class="col-sm-9 buttons-container ">
    <% resource.blends.uniq.each do |blend| %>
        <%= link_to blend, blend_path(blend), colored(blend, class: "btn btn-primary btn-sm blend") %>
    <% end %>
</div>

app/views/substances/add_dilution_to_blend.js.erb
$('.modal.in').modal('hide');
$('[data-dilution=\"<%= @dilution.to_param %>\"] button.btn[data-toggle=\"modal\"]').removeClass('btn-default').addClass('btn-success');

var html = "<%= j render 'used_in_blends' %>";
$('.used-in-blends-container').html(html);

app/views/substances/index.html.erb
<div class="panel panel-primary <%= resource_class_name %>">
    <div class="panel-heading">
        <h3 class="panel-title">
            <%= resource_class.count %> <%= resource_class.model_name.human(count: resource_class.count) %>
            <%= link_to new_substance_path, style: "float:right;" do %>
                <span class="glyphicon glyphicon-plus"></span>
            <% end %>
            <%= link_to refresh_elastic_substances_path, style: "float:right; margin-right: 9px;", class: "refresh-elastic", remote: true, method: :put do %>
                <span class="glyphicon glyphicon-refresh"></span>
            <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <div style="margin-bottom:3ex;">
            <%= render 'character_legend' %>
        </div>
        <%= nav_tabs :substances do |tabs| %>
            <% tabs.add "by name", 'list' %>
            <% tabs.add "by price", 'list', collection: collection.sort{|a,b|(a.price_in_currency_per_100g  || 0 ) <=> (b.price_in_currency_per_100g || 0)  } %>
            <% tabs.add "by VP", 'list', collection: collection.order_vp %>
            <% tabs.add "by character", 'list', collection: collection.order_character %>
            <% tabs.active "compact", 'list_compact' %>
            <% tabs.add "compact c", 'list_compact', collection: collection.order_character %>
        <% end %>
        <%= render 'character_legend' %>
    </div>
    <div class="panel-footer">
        <%= link_to new_substance_path, :class => "btn btn-success" do %>
            <span class="glyphicon glyphicon-plus"></span> <%= t :'global.add' %>
        <% end %>
    </div>
</div>

app/views/substances/index.tex.erb
\title{ALCHEMY\\
Substances}
\author{Henry Stenzel}
\date{\today}
\begin{document}

 
\maketitle
\tableofcontents



<% last_character = nil %>
<% Substance.order_character.each do |substance| %>
 
    <% if substance.character.present? && substance.character.to_s.strip != last_character %>



\<%= tex_c.first %>{<%= etex substance.character.to_s.upcase %>}

    <% end %>
    
<% last_character = substance.character.to_s.strip %>
        

        
\<%= tex_c[1] %>{<%= etex substance.name %>}

\paragraph{<%= Substance.human_attribute_name :cas %> <%= substance.cas %>}

%%price_per_quantity price_currency quantity_in_gram_of_raw_material

<% %w(alt_names).each do |key| %>
<% next if substance.send(key).blank? %>
\paragraph{<%= etex Substance.human_attribute_name key %>}
<%= etex substance.send(key).gsub(/\s*;\s*/,' ; ') %>
<% end %>

<% %w(ifra_cat_4_limit).each do |key| %>
<% next if substance.send(key).blank? %>
\paragraph{<%= etex Substance.human_attribute_name key %>}
<%= number_with_precision substance.send(key) * 100, strip_insignificant_zeros: true %>

<% end %>


<% %w(sensory_tags notes notes_alt_1 notes_alt_2).each do |key| %>
<% next if substance.send(key).blank? %>
\paragraph{<%= etex Substance.human_attribute_name key %>}
<%= tex_readable_links substance.send key %>
<% end %>

<% if substance.dilutions.present? %>



\begin{table}[ht]
\begin{tabular}{lll}
<%= etex Substance.human_attribute_name :dilutions %>\\
\hline
<%= Dilution.human_attribute_name :concentration %> & <%= Dilution.human_attribute_name :solvent %> & <%= Dilution.human_attribute_name :intensity %>\\
\hline
<% substance.dilutions.each do |dilution| %>
<%= number_with_precision dilution.concentration * 100, strip_insignificant_zeros: true %> \% & <%= etex dilution.solvent_human_name %> & <%= dilution.intensity %> \\
<% end %>
\end{tabular}
\end{table}

<% end # of dilutions %>



\pagebreak[3]

<% end # of Substance.all %>

app/views/substances/new_dilution.js.erb
var html = "<%= j render 'new_dilution' %>";

$('form .panel.substance .dilution-form').html(html);

app/views/substances/show.html.erb
<div class="panel panel-primary <%= resource_class_name %>">
    <div class="panel-heading">
        <h3 class="panel-title">
            <%= link_to edit_resource_path(resource), style: 'float: right;', title: "Edit", :'data-toggle' => "tooltip" do %>
                <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= resource.name 
            %><% if resource.cas.present? %>,
                <% first_cas = true %>
                <span style="font-weight: normal; font-size: 12px;">CAS
                    <% resource.cas do |cas| %><%= first_cas ? first_cas = nil : ", "
                        %><%= link_to cas, "https://www.google.de/search?q=cas+#{cas}", target: "_blank" 
                    %> <%= link_to 'pubchem', "http://www.ncbi.nlm.nih.gov/pccompound?term=#{cas}", target: "_blank" 
                    %><% end %>
                </span>
            <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:alt_names), class: 'col-sm-2 small-label' %>
            <div class="col-sm-6">
                <% resource.alt_names do |n| %>
                    <span class="label label-default label-large"><%= n %></span>
                <% end %>
            </div>
            <% if resource.character.present? %>
                <div class="col-sm-4">
                    <h3 style="margin:0; text-align: right;"><span class="label label-default color-<%= resource.character %>" style="color: rgba(0,0,0,0.3);"><%= resource.character.upcase %></span></h3>
                </div>
            <% end %>
        </div>
        <hr/>
        <div class="row">
            <span class='col-sm-2 small-label' style="line-height: 20px;">
                <%= resource_class.human_attribute_name(:ifra_cat_4_limit) %><hr/>
                <%= resource_class.human_attribute_name(:vp_mmHg_25C) %>
            </span>
            <div class="col-sm-2">
                <%= "#{ number_with_precision(resource.ifra_cat_4_limit * 100, precision: 3)} %" rescue "unregulated"  %><hr/>
                <%= resource.vp_mmHg_25C ? number_with_precision( resource.vp_mmHg_25C, precision: 9, strip_insignificant_zeros: true) : "&nbsp;".html_safe %>
            </div>
            <div class="col-sm-4">
                <% resource.cas do |c| %>
                    <%= image_tag molecule_substance_path(resource, cas: c), data: { toggle: 'tooltip', placement: 'bottom' }, title: c %>
                <% end %>
            </div>
        </div>
        <hr/>

        <% if resource.price_per_quantity.to_f > 0 && resource.quantity_in_gram_of_raw_material > 0 %>
            <div class="row">
                <%= content_tag :span, resource_class.human_attribute_name(:price), class: 'col-sm-2 small-label' %>
                <div class="col-sm-9">
                    <% if resource.price_per_quantity.to_s != "EUR" || resource.quantity_in_gram_of_raw_material != 100 %>
                      <%= number_with_precision resource.price_per_quantity %> <%= resource.price_currency %> per <%= resource.quantity_in_gram_of_raw_material %> gram <br/>
                    <% end %>
                    <%= number_with_precision resource.price_in_eur_per_100g %> EUR per 100 gram <br/>
                </div>
            </div>
            <hr/>
        <% end %>
        <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:sensory_tags), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <% resource.sensory_tags.split(/\b/).each do |tag| %>
                    <%= link_to tag, search_path(:q => tag) %>
                <% end %>
            </div>
        </div>
        <hr/>
        <% [:notes, :notes_alt_1, :notes_alt_2 ].each do |field| %>
            <% next unless resource.send(field).present? %>
            <div class="row">
                <%= content_tag :span, resource_class.human_attribute_name(field), class: 'col-sm-2 small-label' %>
                <div class="col-sm-9">
                    <%= smarted resource.send field %>
                </div>
            </div>
            <hr/>
        <% end %>
        <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:dilutions), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= render resource.dilutions %>
            </div>
        </div>
        <hr/>
        <div class="row used-in-blends-container">
            <%= render "used_in_blends" %>
        </div>
    </div>
    <div class="panel-footer">
    </div>
</div>
<p>
    <%= link_to substances_path, :class => "btn btn-default" do %>
        <span class="glyphicon glyphicon-th-list"></span> Index
    <% end %>
</p>

<%= render "add_to_blend_modal" %>

app/views/substances/suggest.js.erb
console.log("substances:");
console.log("<%= j @suggest.inspect %>");
 
console.log("blends:");
console.log("<%= j @blends_suggest.inspect %>");

var html = "<%= j render '/search/autocomplete_dropdown' %>";

$('#psf-autocomplete-dropdown').replaceWith(html);