config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  resources :solvents
  
  resources :substances do
    member do
      get :molecule
      get :new_dilution
      post :add_dilution_to_blend
    end
    collection do
      get :new_dilution
      get :suggest
      get :report
      put :refresh_elastic
    end
  end
  
  resources :blends do
    member do
      post :bottle
      post :adjust
      post :resize
      get :dilute
      get :print
      put :detach_families
    end
    collection do
      get :memorize
      put :refresh_elastic
    end
  end
  
  resources :families do
    member do
      get :add_blends
    end
  end
  
  resources :olfactive_families, controller: "olfactive_families"
  
  resource :mixing, :controller => "mixing" do
    member do
      get :new
      post :prepare
      get :prepare
      post :create
      get :update_final_concentration
    end
  end

  resources :separating do
    member do
      get :prepare
      post :create
    end
  end
  
  resource :analyzer, controller: "analyzer" do
    get :comparison
    get :new
  end
  
  resources :notes
  
  resource :search, :controller => "search"
  
  resource :welcome, :controller => "welcome" do
    get :help
  end
  
  match "set/:key/:value", :controller => "welcome", :action => "set_session_variables", via: [:get, :post]
  
  
  

end

app/models/family.rb
class Family < ActiveRecord::Base
  
  scope :root, lambda { where :parent_id => nil }
  scope :visible, lambda { root }
  scope :hidden, lambda { where :parent_id => true }
  
  belongs_to :parent, class_name: "Family", foreign_key: :parent_id
  has_many :children, class_name: "Family", foreign_key: :parent_id
  has_and_belongs_to_many :blends
  
  validates :name, uniqueness: true, presence: true
  
  def to_s
    name
  end
  
  def selected_blend_ids
    blends.pluck "concat('blend_', blend_id)"
  end
  
  def selected_blend_ids=(seds)
    ids = seds.split(" ").map{|s| s.gsub(/\Ablend_/, '').to_i if s[/\Ablend_/] }.compact
    seds = ids.dup
    ids -= blend_ids
    rems = blend_ids - seds
    blends << Blend.where( id: ids )
    blends.delete Blend.where( id: rems )
  end

end

app/controllers/families_controller.rb
class FamiliesController < InheritedResources::Base

  private
  
  def family_params
    # It's mandatory to specify the nested attributes that should be whitelisted.
    # If you use `permit` with just the key that points to the nested attributes hash,
    # it will return an empty hash.
    params.require(:family).permit( :parent_id, :name, :color, :tags, :notes, :selected_blend_ids )
  end
  
  def root_families
    collection.root
  end
  
  def build_resource
    super.tap do |res|
      if params[:parent_id]
        if parent = resource_class.find(params[:parent_id]) rescue nil
          resource.color = parent.color
          if parent.name.strip[/\s\d{1,4}\z/]
            number = parent.name.strip[/\d+\z/].to_i + 1
            resource.name = "#{parent.name.gsub(/\d+\z/,'')} #{number}"
          elsif parent.name.strip[/\s\w{1,2}\z/] && 0 < (deputy = parent.name.strip[/\w+\z/].to_i(36))
            resource.name = "#{parent.name.gsub(/\w+\z/,'')} #{(deputy + 1).to_s(36).upcase}"
          else
            resource.name = "#{parent.name} Sub"
          end
          resource.tags = parent.tags
          resource.parent = parent
          @parent = parent
        end
      end
    end
  end
  
end

app/views/families/_element.html.erb
<% element = element.to_sym %>
<div class="row">
    <%= content_tag :span, resource_class.human_attribute_name(element), class: 'col-sm-2 small-label' %>
    <div class="col-sm-9">
        <% if element == :parent %>
             <%= link_to resource.parent, resource.parent, colored(resource.parent, class: "btn btn-default btn-sm") %>
        <% elsif element == :notes %>
            <%= smarted resource.notes %>
        <% elsif element == :children %>
            <div class="buttons-container">
                <% resource.children.each do |child| %>
                    <%= link_to child, child, colored(child, class: "btn btn-default btn-sm") %>
                <% end %>
            </div>
        <% elsif element == :blends %>
            <% if true || resource.blends.size > 7 %>
                <%= nav_tabs :blend_tabs do |tabs| %>
                    <% tabs.add "Detail", 'blends/list', collection: resource.blends %>
                    <% tabs.add "ABC", 'blends/list', collection: resource.blends.order_name %>
                    <% tabs.add "by creation at", 'blends/list_short_by_creation_at', collection: resource.blends %>
                    <% tabs.active "Compact", 'list_short', collection: resource.blends %>
                <% end %>
            <% else %>
                <%= render 'blends/list_short', collection: resource.blends, nopanel: true %>
            <% end %>
        <% else %>
            <%= resource.send element %>
        <% end %>
    </div>
</div>

app/views/families/_family.html.erb
<tr>
    <%= content_tag :td, colored(family) do %>
        <%= render 'family_link', family: family %>
    <% end %>
    </td>
    <td>
        <%= family.tags %>
    </td>
</tr>

app/views/families/_family_link.html.erb
<% family ||= family_link %>
<%= link_to family, colored(family, class: "btn btn-default btn-sm family-link", :'data-dom-id' => dom_id(family) )  do -%>
    <%= family %>
    <% if family.parent_id -%>
        <span class="glyphicon glyphicon-link"></span>
    <% end %>
<% end %>

app/views/families/_form.html.erb
<%= render 'form_group_error_messages' %>

<div class="form-group form-group-lg <%= :'has-error' if :parent_id.in? f.object.errors %>">
    <%= f.label :parent_id, :class => "col-sm-3 control-label" %>
    <div class="col-sm-6">
        <%= f.select :parent_id,
        options_for_select(Family.all.collect { |s| [ s.name, s.id ] }, resource.parent_id), {prompt: 'Select parent family if this is a sub-category', include_blank: 'No Parent'}, class: "form-control"  %>
    </div>
    <div class="col-sm-3">
        <%= link_to "COLOR", "#", class: "btn btn-default ", style: "font-weight:900; color:rgba(0,0,0,0.2); width: 100%; background-color:##{f.object.color};", :'data-colorpicker' => "button"  %>
        <%= f.hidden_field :color, :'data-colorpicker' => '' %>
    </div>
    <div data-colorpicker="flat" style="display:none;"></div>
</div>
<hr/>
<div class="form-group form-group-lg <%= :'has-error' if :name.in? f.object.errors %>">
    <%= f.label :name, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
        <%= f.text_field :name, :class => "form-control", :style => "font-weight: bold;", autocomplete: "off" %>
    </div>
</div>
<hr/>
<%= render 'text_area_form_group', f: f, c: :tags %>
<hr/>
<%= render 'text_area_form_group', f: f, c: :notes, opt: { rows: 5 } %>

<% content_for :panel_footer do %>
    <div class"form-group">
    </div>
<% end %>


<% content_for :form_submit_controls do %>
    <div class="form-inline">
        <div class"form-group">
            <%= f.submit submit_label, :class => "btn btn-#{submit_class ||= :success} col-sm-offset-9 col-sm-3" %>
        </div>
    </div>
<% end %>

app/views/families/_list.html.erb
<table class="table table-condensed">
    <thead>
        <tr>
            <th><%= resource_class.human_attribute_name :name %></th>
            <th><%= resource_class.human_attribute_name :tags %></th>
        </tr>
    </thead>
    <tbody>
        <%= render collection %>
    </tbody>
</table>

app/views/families/_list_short.html.erb
<div class="panel-body buttons-container">
    <% collection.each do |record| %>
        <%= blend_link record, o: colored(record, class: "btn btn-default btn-sm") %>
    <% end %>
</div>

app/views/families/add_blends.html.erb
<%= form_for resource, :html => {:class => 'family-batch-add', :role => "form"} do |f| %>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">
                Add <%= Blend.model_name.human(count: 2) %> to <%= Family.model_name.human(count: 1) %> <%= resource %>
            </h3>
        </div>
        <div class="panel-body buttons-container">
            <h4><%= t :'global.available', count: 2 %> <%= Blend.model_name.human(count: 2) %></h4>
            <div class="available-blends">
                <% (Blend.all - resource.blends).each do |record| %>
                    <%= link_to record.to_s, "#", colored(record, class: "btn btn-default btn-sm", :'data-blend-dom-id' => dom_id(record) ) %>
                <% end %>
            </div>
            <hr/>
            <h4><%= t :'global.selected', count: 2 %> <%= Blend.model_name.human(count: 2) %></h4>
            <div class="selected-blends">
                <% resource.blends.each do |record| %>
                    <%= link_to record.to_s, "#", colored(record, class: "btn btn-default btn-sm", :'data-blend-dom-id' => dom_id(record) ) %>
                <% end %>
            </div>
            <%= f.hidden_field :selected_blend_ids, class: resource.selected_blend_ids, id: :selected_blend_ids %>
        </div>
        <div class="panel-footer">
            <%= link_to t(:'global.cancel'), resource, class: 'btn' %>
            <button type="submit" class="btn btn-primary disabled">
                <span class="glyphicon glyphicon-log-in"></span> <%= t :'global.add' %>
            </button>
        </div>
    </div>
<% end %>

app/views/families/index.html.erb
<div class="panel panel-primary <%= resource_class_name %>">
    <div class="panel-heading">
        <h3 class="panel-title">
            <%= resource_class.count %> <%= resource_class.model_name.human(count: resource_class.count) %>
            <%= link_to new_resource_path, style: "float:right;" do %>
                <span class="glyphicon glyphicon-plus"></span>
            <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <%= nav_tabs :family_tabs do |tabs| %>
            <%# tabs.add "Detail", 'list' %>
            <% tabs.active "Compact", 'list_compact', collection: collection.root %>
            <% tabs.add "All", 'list_compact' %>
        <% end %>
    </div>
    <div class="panel-footer">
        <%= link_to new_resource_path, :class => "btn btn-success" do %>
            <span class="glyphicon glyphicon-plus"></span> <%= t :'global.add' %>
        <% end %>
    </div>
</div>

app/views/families/show.html.erb
<div class="panel panel-primary <%= resource_class_name %> <%= bg_color_class(resource.color) %>" style="border-color:#<%= resource.color %>;">
    <div class="panel-heading" style="background-color:#<%= resource.color %>; border-color:#<%= resource.color %>;">
        <h3 class="panel-title">
            <div class="topright-controls">
                <%= link_to edit_resource_path(resource), title: "Edit", :'data-toggle' => "tooltip" do %>
                    <span class="glyphicon glyphicon-edit"></span>
                <% end %>
            </div>
            <%= resource.name %>
        </h3>
    </div>
    <div class="panel-body">
        <%= render partial: 'element', collection: select_present(resource, :parent, :tags, :notes, :children, :blends), spacer_template: 'layouts/hr' %>
    </div>

    <div class="panel-footer">
        <%= link_to new_mixing_path(family_id: resource.id), {class: "btn btn-success"} do %>
            <span class="glyphicon glyphicon-random"></span> Mix!
        <% end %>
        <%= link_to new_analyzer_path(family_id: resource.id), {class: "btn btn-info"} do %>
            <span class="glyphicon glyphicon-random"></span> Analyze!
        <% end %>
        <%= link_to add_blends_family_path(resource), {class: "btn btn-default"} do %>
            <span class="glyphicon glyphicon-log-in"></span> <%= t :'global.manage_memberships' %>
        <% end %>
        <%= link_to url_for(action: :new, parent_id: resource.id), class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-th"></span> <%= t :'global.add_subcategory' %>
        <% end %>
    </div>
</div>
<p>
    <%= link_to url_for(action: :index), {class: "btn btn-default"} do %>
        <span class="glyphicon glyphicon-th-list"></span> Index
    <% end %>
</p>