config/routes.rb
Rails.application.routes.draw do
  
  
  root 'welcome#index'
  
  resources :solvents
  
  resources :substances do
    member do
      get :molecule
      get :new_dilution
      post :add_dilution_to_blend
    end
    collection do
      get :new_dilution
      get :suggest
      get :report
      put :refresh_elastic
    end
  end
  
  resources :blends do
    member do
      post :bottle
      post :adjust
      post :resize
      get :dilute
      get :print
      put :detach_families
    end
    collection do
      get :memorize
      put :refresh_elastic
    end
  end
  
  resources :families do
    member do
      get :add_blends
    end
  end
  
  resources :olfactive_families, controller: "olfactive_families"
  
  resource :mixing, :controller => "mixing" do
    member do
      get :new
      post :prepare
      get :prepare
      post :create
      get :update_final_concentration
    end
  end

  resources :separating do
    member do
      get :prepare
      post :create
    end
  end
  
  resource :analyzer, controller: "analyzer" do
    get :comparison
    get :new
  end
  
  resources :notes
  
  resource :search, :controller => "search"
  
  resource :welcome, :controller => "welcome" do
    get :help
  end
  
  match "set/:key/:value", :controller => "welcome", :action => "set_session_variables", via: [:get, :post]
  
  
  

end

app/models/blend.rb
class Blend < ActiveRecord::Base

  include Blend::Searchable
  include CasAble
  
  LOCKED_CHANGEABLE = %w(locked sensory_tags notes color)
  
  scope :order_name, -> { order("#{self.table_name}.name ASC") }
  scope :order_updated_at, -> { order("#{self.table_name}.updated_at DESC") }
  scope :order_creation_at, -> { order("#{self.table_name}.creation_at DESC") }#
  scope :visible, lambda { where :hidden => false }
  scope :hidden, lambda { where :hidden => true }
  scope :locked, lambda { where :locked => true }
  
  belongs_to :parent, class_name: "Blend", foreign_key: :parent_id

  has_many :ingredients, dependent: :destroy
  has_many :dilutions, through: :ingredients
  has_many :substances, through: :ingredients
  has_many :children, class_name: "Blend", foreign_key: :parent_id
  
  has_and_belongs_to_many :families
  
  accepts_nested_attributes_for :ingredients, allow_destroy: true # reject_if: proc { |attributes| attributes['title'].blank? }

  validates :name, uniqueness: true
  validates :name, :ingredients, :presence => true

  validates_associated  :ingredients
  
  before_destroy :before_destroy
  before_save    :careful_save
  
  def to_s
    name
  end
  
  def exceeding_cat_4?
    exceeders.present?
  end
  
  def exceeders
    @exceeders ||= get_exceeders
  end
  
  def maximum_allowed_concentration
    exceeders
    @exceedance && 1.0 / @exceedance * concentration
  end
  
  def components
    @components ||= get_components
  end
  
  def get_components
    @components = {}
    ingredients.includes(:substance, :dilution).each do |ing|
      tmp_component = Component.new(ing, self)
      add_to_components(tmp_component)
      if tmp_component.substance? && ing.concentration < 1.0
        add_to_components Component.new_for_solvent(ing, self)
      end
    end
    @components.values.sort{|b,a| a.mass <=> b.mass }
  end
  
  def get_exceeders
    m = total_mass.to_f
    @exceedance = 1.0
    exceeders = []
    components.each do |com|
      next if com.molecule.is_a?(Solvent)
      next unless com.molecule.ifra_cat_4_limit
      c = com.mass / m
      if com.molecule.ifra_cat_4_limit < c
        exceeders << com.molecule 
        @exceedance = c / com.molecule.ifra_cat_4_limit
      end
    end
    exceeders
  end

  def composition
    cc = {}
    ingredients.each do |ing|
      # substance
      ing = Ingredient.new(ing.clone_attributes)
      next if ing.dilution && ing.dilution.concentration.to_f == 0
      amount = ing.amount * (ing.dilution.concentration rescue 1.0)
      if cc[ing.substance_id]
        cc[ing.substance_id].amount += amount
      else
        ing.amount = amount
        cc[ing.substance_id] = ing
      end
    end
    
    # TODO SOLVENTS => new calculations needed after new solvent model
    
    ingredients.clone.each do |ing|
      # solvent
      ing = Ingredient.new(ing.clone_attributes)
      next if !ing.dilution || ing.dilution.concentration == 1.0
      s_amount = ing.amount * (1.0 - ing.dilution.concentration)
      key = "solvent_#{ing.dilution.solvent.id rescue rand(1e16) }"
      if cc[key]
        cc[key].amount += s_amount
      else
        ing.amount = s_amount
        cc[key] = ing
      end
    end
    cc
  end
  
  def essence_composition(sort_by=nil)
    cc = {}
    ingredients.each do |ingo|
      ing = Ingredient.new(ingo.clone_attributes)
      next if ingo.dilution && ingo.dilution.concentration.to_f == 0
      amount = ing.amount * (ingo.dilution.concentration rescue 1.0)
      if cc[ing.substance_id]
        cc[ing.substance_id].amount += amount
      else
        ing.amount = amount
        cc[ing.substance_id] = ing
      end
    end
    if sort_by == :vp
      return cc.values.sort{|a,b| a.substance.vp_mmHg_25C.to_f <=> b.substance.vp_mmHg_25C.to_f }
    elsif sort_by == :hashed
      cc
    else
      return cc.values.sort{|a,b| a.amount <=> b.amount }.reverse
    end
  end
  
  def essence_proportions(sort_by=nil)
    cc = {}
    ingredients.each do |ingo|
      next if ingo.solvent_only?
      com = Component.new(ingo)
      if cc[com.cid]
        cc[com.cid].mass += com.mass
      else
        cc[com.cid] = com
      end
    end
    if sort_by == :vp
      return cc.values.sort{|a,b| a.molecule.vp_mmHg_25C.to_f <=> b.molecule.vp_mmHg_25C.to_f }
    elsif sort_by == :hashed
      cc
    else
      return cc.values.sort{|a,b| a.mass <=> b.mass }.reverse
    end
  end
  
  
  def character_proportions
    return {} unless (weight = essence_mass)
    cp = {}
    ingredients.each do |ing|
      # substance
      next if ing.dilution && ing.dilution.concentration.to_f == 0
      percent = ing.amount * (ing.dilution.concentration rescue 1.0) / weight.to_f * 100.0
      name = ing.substance.character || :unknown
      if cp[name]
        cp[name] += percent
      else
        cp[name] = percent
      end
    end
    cp
  end
  
  def raw_price
    return @raw_price if @raw_price 
    price = 0.0
    ingredients.each do |ing|
      next if ing.dilution && ing.dilution.concentration.to_f == 0
      amount = ing.amount * (ing.dilution.concentration rescue 1.0)
      price += amount * ing.substance.price_in_eur_per_100g.to_f * 0.00001 
    end
    @raw_price = price
  end
  
  def price_per_gram(m=100000)
    raw_price * ( m.to_f / total_mass.to_f)
  end
  
  def total_mass
    ingredients.sum(:amount).to_f
  end

  def essence_mass
    c_v = 0
    ingredients.each do |ing|
      c_v += ing.amount * (ing.dilution.concentration rescue 1.0)
    end
    c_v.to_f
  end
  
  # without additional solvents
  def ingredient_weight
    total_mass - additional_solvents_amount
  end
    
  def concentration
    essence_mass / total_mass
  end
  
  def resize!(opts={})
    success = true
    return nil unless total_mass.to_f > 0
    if opts[:factor].to_f > 0
      scale = opts[:factor].to_f
    elsif opts[:mg].to_f > 0
      scale = opts[:mg].to_f / total_mass.to_f
    else
      return nil
    end
    ingredients.each do |ing|
      ing.amount = ing.amount * scale
      success = false unless ing.save
    end
    success
  end

  def additional_solvents_amount
    sum = 0.0
    ingredients.each do |ing|
      sum += ing.amount if ing.dilution && ing.dilution.concentration == 0.0
    end
    sum.to_f
  end
  
  def max_concentration
    essence_mass / (total_mass - additional_solvents_amount)
  end
  
  def adjust!(new_concentration)
    if new_concentration < max_concentration
      new_mass = (essence_mass / new_concentration)
      ing_m = total_mass - additional_solvents_amount
      nasm = new_mass - ing_m
      ratio = (nasm) / additional_solvents_amount
      return total_mass if adjust_solvents_by!(ratio)
    else
      return false
    end
  end
  
  def adjust_solvents_by!(ratio)
#    puts ratio.to_s
    success = true
    ingredients.each do |ing|
      next unless ing.dilution && ing.dilution.concentration == 0.0
      ing.amount *= ratio
      success = false unless ing.save
    end
    success
  end
  
  def unlock_silent
    self.locked = false
    @skip_carefulness = true
  end
  
  protected
  
  def add_to_components(tmp_component)
    key = tmp_component.molecule
    if tmp_component.substance? || tmp_component.molecule.pure?
      if @components[key]
        @components[key].add(tmp_component)
      else
        @components[key] = tmp_component
      end
    else
      # solvents molecular components
      tmp_component.molecule.molecular_composition.each do |mol|
        com = Component.new(mol, self)
        com.mass = tmp_component.mass * mol.virtual_proportion
        add_to_components com
      end
    end
  end
  
  def before_destroy
    return true unless locked?
    errors.add :id, "cannot delete locked record"
    false
  end
  
  def careful_save
    return true if careful_save_allowed
    (changes.keys - ["locked"]).each do |ke|
      errors.add ke, "cannot change locked record"
    end
    false
  end
  
  private
  
  def careful_save_allowed
    return true if @skip_carefulness
    return true unless locked?
    just_locked || locked_changeable
  end
  
  def just_locked
    changes["locked"] == [false, true]
  end

  def locked_changeable
    (changes.keys - LOCKED_CHANGEABLE).blank?
  end
  
end

app/models/concerns/blend/searchable.rb
module Blend::Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    
    index_name table_name

    mapping do
      indexes :name, analyzer: 'english', index_options: 'offsets'
      indexes :name_suggest, type: 'completion', payloads: true, index_analyzer: "simple", search_analyzer: "simple"
      indexes :sensory_tags, analyzer: 'english', index_options: 'offsets'
      indexes :notes, analyzer: 'english', index_options: 'offsets'
    end

  end


  def as_indexed_json(options = {})
     {
       name: name,
       sensory_tags: sensory_tags,
       notes: notes,
       name_suggest: {
         input: name.split(/\b/),
         output: name,
         payload: {
           resource_id: id,
           color: color
         }
       }
     }
   end
     
end

app/controllers/blends_controller.rb
class BlendsController < InheritedResources::Base
  
  include Memorizable
  include ActionView::Helpers::JavaScriptHelper
  
  helper_method :blends_for_parentship
  
  def adjust
    target_c = to_f(params[:concentration]) / 100.0
    resource.adjust! target_c
    redirect_to resource
  end

  def bottle
    respond_to do |format|
      format.js do
        target_mg = to_f(params[:amount_in_mg])
        if ( target_mg > 0 || params[:amount_in_mg] == "" ) && params[:new_blend_name].present?
          new_bottle = resource_class.new(resource.attributes)
          new_bottle.unlock_silent
          new_bottle.name = params[:new_blend_name]
          new_bottle.id = nil
          new_bottle.parent = resource
          new_bottle.families = resource.families
          new_bottle.ingredients = []
          resource.ingredients.each do |ing|
            ing.id = nil
            ing.blend = nil
            new_bottle.ingredients << Ingredient.new(ing.attributes)
          end
          success = new_bottle.save
          success = new_bottle.resize!(mg: target_mg) if target_mg > 0
          if new_bottle.errors.empty? && success
            render js: "window.location ='#{url_for new_bottle}';"
          else
            render js: "alert('#{new_bottle.errors.full_messages.join(" - ")} \\n #{j new_bottle.inspect}');"
          end
        else
          render js: "alert('Please fill out all fields');"
        end
      end
    end
  end

  def resize
    respond_to do |format|
      format.js do
        if to_f(params[:gram]) > 0 && params[:strategy].to_s[/gram/]
          resize! mg: to_f(params[:gram]) * 1000
        elsif to_f(params[:mg]) > 0 && params[:strategy].to_s[/mg/]
          resize! mg: to_f(params[:mg])
        elsif to_f(params[:factor]) > 0 && params[:strategy].to_s[/factor/]
          resize! factor: to_f(params[:factor])
        else
          render js: "alert('Please fill out all fields');"
        end
      end
    end
  end
  
  def detach_families
    respond_to do |format|
      format.js do
        if (dom_ids = params[:dom_ids])
          ids = []
          deleted_dom_ids = []
          dom_ids.each do |did|
            if (did[/\Afamily_\d+\z/])
              ids << did[/\d+\z/].to_i
              deleted_dom_ids << did
            end
          end
          resource.families.delete Family.where(id: ids)
          dom_selectors = deleted_dom_ids.map do |did|
            "[data-dom-id=\"#{did}\"]"
          end
          render js: " $('.family.droparea.devnull').find('#{dom_selectors.join(',')}').hide('fade'); $('.family.droparea.devnull').delay(300).hide('puff');"
        else
          render js: "alert('422 parameters missing');", status: 422
        end
      end
    end
  end
  
  def refresh_elastic
    respond_to do |format|
      format.js do
        Blend.import force: true
        render js: "$('a.refresh-elastic').remove();"
      end
    end
  end
  
  def print
    render layout: 'print'
  end

  private
  
  def build_resource
    super.tap do |res|
      begin
        res.families << Family.where(id: params[:family_ids].to_s.split(',')) if params[:family_ids].present?
      rescue Exception => e
        raise params[:family_ids].inspect
      end
    end
  end
  
  def blends_for_parentship
    []
    if resource && resource.families
      b1 = resource.families.map(&:blends).flatten.compact.uniq
      pfs = resource.families.map(&:parent).flatten.compact.uniq
      if pfs.present? && ( pfs_blends = pfs.map(&:blends).flatten.compact.uniq).present?
        delim = '-----------'
        delim.extend MockNameable
        pfs -= b1
        return [b1, delim, pfs_blends].flatten if pfs.present?
      else
        return b1
      end
    end
    
    Blend.all
  end
  
  def to_f(f)
    I18n.delocalization_enabled? ? Numeric.parse_localized(f).to_f : f.to_f
  end
  
  def resize!(opts)
    return render js: "alert('cannot resize locked blend');" if resource.locked?
    if resource.resize! opts
      turbo_reload
    else
      render js: "alert('unknown error');"
    end
  end
  
  def blend_params
    # It's mandatory to specify the nested attributes that should be whitelisted.
    # If you use `permit` with just the key that points to the nested attributes hash,
    # it will return an empty hash.
    params.require(:blend).permit(:name, :creation_at, :sensory_tags, :notes, :color, :locked, :hidden, :parent_id, :family_ids,
      ingredients_attributes: [:substance_id, :amount, :dilution_id, :highlighted, :id, :_destroy ]
    )
   end
  
end

app/helpers/blends_helper.rb
module BlendsHelper

  def blend_link(blend, options={})
    options[:blend] = blend
    render '/blends/blend_link', options
  end

  # TODO use ElasticSearch here to get blends by tags count for performance increase
  def blends_by_tags
    tcg = Blend.pluck(:sensory_tags).flatten.join(' ').gsub(/\W+/,' ').split(' ').uniq
    tcg = tcg.sort!
    ordered = {}
    all_blends = Blend.all.to_a
    tcg.each do |tc|
      tag = tc.downcase
      ordered[tag] = all_blends.select{|blend| blend.sensory_tags[/\b#{tag}\b/i] }.to_a
    end
    Rails.logger.info ordered.keys
    ordered.values.each do |vv|
      Rails.logger.info vv.map &:name
    end
    ordered
  end
  
  def get_precision(float, ref=5)
    if params[:precision].nil? || params[:precision].to_s.downcase.to_sym == :auto
      precision = (ref - Math.log10(float)).round
      precision = 1 if precision < 2
      precision = 4 if precision == 3
      return precision
    elsif params[:precision]
      return params[:precision].to_i
    end
  end
  
  def precision_manually_zeroed?
    params[:precision] && params[:precision].to_i == 0
  end

end

app/views/blends/_blend.html.erb
<tr class="<%= :translucent if blend.hidden? %>">
    <%= content_tag :td, colored(blend) do %>
        <%= blend_link blend, style: "width: 100%; display:block;" %>
    <% end %>
    <% unless :concentration.in? @supress.to_a %>
        <td><%= number_with_precision blend.concentration * 100.0 %> %</td>
    <% end %>
    <td style="white-space: nowrap;"><%= blend.creation_at %></td>
    <td><%= blend.sensory_tags %></td>
</tr>

app/views/blends/_blend_link.html.erb
<% options = {} -%>
<% options = o if defined?(o) -%>
<% options[:style] = style if defined?(style) -%>
<% options[:class] = css_class if defined?(css_class) -%>
<%= link_to blend_path(blend), options do -%>
    <%= blend.name %>
    <% if blend.locked? -%>
        <span class="glyphicon glyphicon-lock"></span>
    <% end %>
    <% if blend.hidden? -%>
        <span class="glyphicon glyphicon-eye-close"></span>
    <% end %>
    <% if blend.parent_id -%>
        <span class="glyphicon glyphicon-link"></span>
    <% end %>
<% end %>

app/views/blends/_ingredient_form.html.erb
<%= f.fields_for :ingredients do |fd| %>
    <div class="form-group">
        <%= fd.hidden_field :highlighted, class: 'highlight' %>
        <%= f.label :ingredient, Ingredient.model_name.human, class: "col-sm-3 control-label #{:highlighted if fd.object.highlighted}", data: { toggle: :highlight }  %>
        <div class="col-sm-2 <%= :'has-error' if :amount.in?(fd.object.errors) %>">
            <%= fd.text_field :amount, placeholder: :mg, class: 'form-control', precision: prec(fd.object.amount,4), strip_insignificant_zeros: true, autocomplete: "off" %>
        </div>
        <div class="col-sm-3 <%= :'has-error' if :substance.in?(fd.object.errors) %>">
            <%= fd.select :substance_id, Substance.all.collect { |s| [ s.name, s.id ] }, {prompt: 'Substance'}, class: "form-control substance having-dilution-select"  %>
        </div>
        <div class="col-sm-3 <%= :'has-error' if :dilution.in?(fd.object.errors) %>">
            <%= render 'dilution_select', fd: fd %>
        </div>
        <div class="col-sm-1 <%= :nodisplay if fd.object.locked? %>">
            <%= fd.link_to_remove class: "btn" do %>
                <span class="glyphicon glyphicon-trash"></span>
            <% end %>
        </div>
    </div>
<% end %>

app/views/blends/_resize_modal.html.erb
<div class="modal fade" id="resize-wizard" tabindex="-1" role="dialog" aria-labelledby="Resize Wizard" aria-hidden="true">
    <div class="modal-dialog">
        <%= form_tag resize_blend_path(resource), remote: true do %>
            <%= hidden_field_tag :strategy, 'factor' %>
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel"><%= t :'view.resize.title' %></h4>
                </div>
                <div class="modal-body">
                    <%= nav_tabs :resize_tabs do |tabs| %>
                        <% tabs.active "by factor", 'resize_by_factor' %>
                        <% tabs.add "to gram", 'resize_to_total_mass' %>
                        <% tabs.add "to mg", 'resize_to_mg' %>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t :'global.cancel' %></button>
                    <button type="submit" class="btn btn-primary"><%= t :'view.resize.action' %> <span class="glyphicon glyphicon-sort"></span></button>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/blends/index.html.erb
<div class="panel panel-primary <%= resource_class_name %>">
    <div class="panel-heading">
        <h3 class="panel-title">
            <%= resource_class.count %> <%= resource_class.model_name.human(count: resource_class.count) %>
            <%= link_to new_resource_path, style: "float:right;" do %>
                <span class="glyphicon glyphicon-plus"></span>
            <% end %>
            <%= link_to refresh_elastic_blends_path, style: "float:right; margin-right: 9px;", class: "refresh-elastic", remote: true, method: :put do %>
                <span class="glyphicon glyphicon-refresh"></span>
            <% end %>
        </h3>
    </div>
    <div class="panel-body">
        <% @supress = [:concentration] %>
        <%= nav_tabs :blend_tabs do |tabs| %>
            <% tabs.add "Detail", 'list' %>
            <% tabs.add "ABC", 'list', collection: collection.order_name %>
            <% tabs.add "by creation at", 'list_short_by_creation_at' %>
            <% tabs.add "by updated_at",  'list_short_by_updated_at' %>
            <% tabs.add "by tags", 'list_short_by_tags' %>
            <% tabs.active "Compact", 'list_short', collection: collection.visible %>
            <% tabs.add "Hidden", 'list_short', collection: collection.hidden %>
        <% end %>
    </div>
    <div class="panel-footer">
        <%= link_to new_resource_path, :class => "btn btn-success" do %>
            <span class="glyphicon glyphicon-plus"></span> <%= t :'global.add' %>
        <% end %>
        <%= link_to new_mixing_path, :class => "btn btn-primary" do %>
            <span class="glyphicon glyphicon-random"></span> Mix
        <% end %>
    </div>
</div>

app/views/blends/show.html.erb
<div class="panel panel-primary <%= resource_class_name %> <%= bg_color_class(resource.color) %>" style="border-color:#<%= resource.color %>;">
    <div class="panel-heading" style="background-color:#<%= resource.color %>; border-color:#<%= resource.color %>;">
        <h3 class="panel-title">
            <div class="topright-controls">
                <%= link_to '<span class="glyphicon glyphicon-print"></span>'.html_safe, { action: :print, precision: 0 }, data: { :'no-turbolink' => '' } %>
                <% unless resource.locked? %>
                    <%= link_to dilute_blend_path(resource) do %>
                        <span class="glyphicon glyphicon-wrench"></span>
                    <% end %>
                    <%= link_to edit_resource_path(resource), title: "Edit", :'data-toggle' => "tooltip" do %>
                        <span class="glyphicon glyphicon-edit"></span>
                    <% end %>
                <% else %>
                    <%= link_to edit_resource_path(resource), title: "Edit", :'data-toggle' => "tooltip" do %>
                        <span class="glyphicon glyphicon-lock" data-original-title="locked" data-toggle="tooltip" data-container="body"></span>
                    <% end %>
                <% end %>
            </div>
            <%= resource.name %>, <span style="font-size: 11px;"><%= resource.creation_at %></span>
        </h3>
    </div>
    <div class="panel-body">
        <% fnpp = resource.families.present? && resource.parent.present? %>
        <% if resource.families.present? || resource.parent.present? %>
            <div class="row">
                <span class="col-sm-2 small-label">
                    <%= resource_class.human_attribute_name(:parent) if resource.parent.present? %><%
                        if fnpp %>, <br/><% end %>
                    <%= Family.model_name.human(count: resource.families.count ) if resource.families.present? %>
                </span>
                <%= if resource.parent ; content_tag :div, class: "col-sm-3 #{:brr if fnpp}" do %>
                    <%= link_to resource.parent, resource.parent, colored(resource.parent, class: "btn btn-default btn-sm") %>
                <% end ; end %>
                <div class="col-sm-6 buttons-container families-drag-detachable">
                    <% resource.families.each do |family| %>
                        <%= render 'families/family_link', family: family %>
                    <% end %>
                </div>
             </div>
             <hr/>
        <% end %>
       <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:sensory_tags), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= resource.sensory_tags %>
            </div>
        </div>
        <hr/>

        <div class="row">
             <%= content_tag :span, resource_class.human_attribute_name(:character), class: 'col-sm-2 small-label' %>
             <div class="col-sm-9">
                 <%= render 'character_strip', blend: resource %>
             </div>
         </div>
         <hr/>

        <div class="row">
            <%= content_tag :span, resource_class.human_attribute_name(:notes), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= smarted resource.notes %>
            </div>
        </div>
        <hr/>
        <div class="row" id="composition">
            <%= content_tag :span, Ingredient.model_name.human(count: 2), class: 'col-sm-2 small-label' %>
            <div class="col-sm-9">
                <%= nav_tabs :composition_as, sticky: true do |tabs| %>
                <%
                    tabs.add "Composition", 'composition'
                    tabs.add "Ingredients", 'ingredients'
                    tabs.add "p2", 'ingredients_2'
                    tabs.active "Normalized", 'normalized'
                    tabs.add "by VP", 'normalized', sort_by: :vp
                end %>
            </div>
        </div>

        <% if resource.children.present? %>
            <div class="row">
                <%= content_tag :span, resource_class.human_attribute_name(:children), class: 'col-sm-2 small-label' %>
                <div class="col-sm-9">
                    <div class="buttons-container">
                        
                    </div>
                    <% resource.children.each do |child| %>
                        <%= link_to child, child, colored(child, class: "btn btn-default btn-sm") %>
                    <% end %>
                </div>
            </div>
        <% end %>

        
     </div>
    <div class="panel-footer <%= :red if resource.exceeding_cat_4? %>">
        <% unless resource.locked? %>
            <button class="btn btn-default" data-toggle="modal" data-target="#resize-wizard">
                <span class="glyphicon glyphicon-sort"></span> <%= t :'view.resize.action' %>
            </button>
        <% end %>
        <button class="btn btn-default" data-toggle="modal" data-target="#bottle-wizard">
            <span class="glyphicon glyphicon-new-window"></span> <%= t :'view.bottling.action' %>
        </button>
        <%= link_to separating_path(resource.id), class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-new-window"></span> <%= t :'global.separate' %>
        <% end %>
        <p style="float:right; line-height: 34px;">
            <span style="margin-right: 1em; opacity: 0.6; font-family: monospace;">
                <strong><%= number_with_precision resource.total_mass.round %> mg</strong>
                (<%= number_with_precision resource.essence_mass.round %> mg)
            </span>
            <% unless resource.locked? %>
                <button class="btn btn-default" data-toggle="modal" data-target="#adjust-wizard">
                    <span class="glyphicon glyphicon-wrench"></span><%= t :'view.adjust.action' %>
                </button>
            <% end %>
            <%= number_with_precision resource.concentration * 100, precision: 1 %> %
            <%= concentration_human resource %>
        </p>
    </div>
</div>
<p>
    <%= link_to blends_path, :class => "btn btn-default" do %>
        <span class="glyphicon glyphicon-th-list"></span> Index
    <% end %>
</p>


<%= render 'adjust_modal', :resource => resource unless resource.locked? %>

<%= render 'bottle_modal', :resource => resource %>

<%= render 'resize_modal', :resource => resource unless resource.locked? %>




<div class="family droparea devnull" style="">
    <div class="background" style="">
        <span class="glyphicon glyphicon-trash"></span>
    </div>
    <a class="btn btn-danger" style="" data-submit-children-path="<%= detach_families_blend_path(resource) %>"><span class="glyphicon glyphicon-trash"></span></a>
    <a class="btn" style="position: absolute; right: 3px; top:3px; width; 50px;" onclick="$('.family.droparea.devnull').hide();">x</a>
</div>